In [4]:
import numpy as np 
import time


In [3]:
arr = np.array([1,3,6,10])
print(arr,type(arr))

[ 1  3  6 10] <class 'numpy.ndarray'>


In [8]:
#performance comaprison 
num =10_000_000 # one million ka data 
list_py = list(range(num))
start = time.time()
sq= [x*x for x in list_py] 
end = time.time()
print(f"the time difference for array is {end-start} seconds")

#numpy_array 
np_array = np.array(list_py)
np_start = time.time()
np_sq_arr = np_array ** 2 
np_end = time.time()
print(f"the time difference between them is {np_end-np_start} seconds")


the time difference for array is 0.8116986751556396 seconds
the time difference between them is 0.026755332946777344 seconds


In [10]:
# memory ka locha 
import sys 
print(f"the size of the list is {sys.getsizeof(list_py)*len(list_py) } bytes ")
print(f"the size of the np array is {np_array.nbytes}")


the size of the list is 800000560000000 bytes 
the size of the np array is 80000000


In [12]:
py_list =["hello",2,6,10,17]
np_arr = np.array(py_list)
print(np_arr,np_arr.dtype,np_arr.shape)

['hello' '2' '6' '10' '17'] <U21 (5,)


In [13]:
#2d array 
np_2D = np.array([ [1,2,3],[4,5,6],[7,8,9]]) 
print(np_2D, np_2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
