In [4]:
import numpy as np 
import time


In [3]:
arr = np.array([1,3,6,10])
print(arr,type(arr))

[ 1  3  6 10] <class 'numpy.ndarray'>


In [8]:
#performance comaprison 
num =10_000_000 # one million ka data 
list_py = list(range(num))
start = time.time()
sq= [x*x for x in list_py] 
end = time.time()
print(f"the time difference for array is {end-start} seconds")

#numpy_array 
np_array = np.array(list_py)
np_start = time.time()
np_sq_arr = np_array ** 2 
np_end = time.time()
print(f"the time difference between them is {np_end-np_start} seconds")


the time difference for array is 0.8116986751556396 seconds
the time difference between them is 0.026755332946777344 seconds


In [10]:
# memory ka locha 
import sys 
print(f"the size of the list is {sys.getsizeof(list_py)*len(list_py) } bytes ")
print(f"the size of the np array is {np_array.nbytes}")


the size of the list is 800000560000000 bytes 
the size of the np array is 80000000


In [12]:
py_list =["hello",2,6,10,17]
np_arr = np.array(py_list)
print(np_arr,np_arr.dtype,np_arr.shape)

['hello' '2' '6' '10' '17'] <U21 (5,)


In [13]:
#2d array 
np_2D = np.array([ [1,2,3],[4,5,6],[7,8,9]]) 
print(np_2D, np_2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [35]:
#array in numpy using inbuilt functions 
a1 = np.zeros((2,4),dtype ="int64") # here dtype ="int64" indicates that is number and not the string ( by defualt) 
print(a1)

a2 = np.ones((3,5),dtype="int64")
print(a2, a2.shape)

a3 = np.full((3,3),5)
print(a3,a3.shape)

a4 = np.eye(3) # sirf ek argument hota hai idhar 
print(a4)

a5 = np.arange(1,10,2)
print(a5,a5.shape)


a6 = np.linspace(1,6,5) 
print(a6,a6.shape)

[[0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]] (3, 5)
[[5 5 5]
 [5 5 5]
 [5 5 5]] (3, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9] (5,)
[1.   2.25 3.5  4.75 6.  ] (5,)


In [37]:
# the propertie of the array 
print(a6.shape) # dimension 
print(a6.size) # total elements 
print( a6.dtype) # type of the array 
print( a6.ndim) # dimention in the numbers 
print( a6. itemsize) # each elemts size in bytes 

(5,)
5
float64
1
8


In [40]:
#some more propertis 
newArr = np.array([[1,2,3],[4,5,6]])
rarr= newArr.reshape((3,2))
print(rarr)

farr = newArr.flatten()
print(farr)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [45]:
#indexing  and slicing  

newArray = np.array([1,4,2,5,2,7,10,17,22])
print(newArray[1]) 
#fancy indexing
idx = [2,4,3]
print(newArray[idx])

#boolean indexing 
print(newArray[newArray%2 !=0 ])

#slicing 
print(newArray[1::2])

4
[2 2 5]
[ 1  5  7 17]
[ 4  5  7 17]


In [50]:
#multi-dimensional array 
a = np.array([ [1,3,5],[7,9,11],[13,15,17]])
s = np.sum(a)
print(a)
print(f"the sum of the array is {s}")
vertical_sum = np.sum(a,axis =0)
print(f"the sum of the vertical lines is {vertical_sum}")
print(f"the sum of horizontal lines is {np.sum(a,axis=1)}")
#slicing the array is done by 
print(f"the sub part of the array is {a[0:2,1:2]}")
print(f"{a[0::2, 0::2]}")

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
the sum of the array is 81
the sum of the vertical lines is [21 27 33]
the sum of horizontal lines is [ 9 27 45]
the sub part of the array is [[3]
 [9]]
[[ 1  5]
 [13 17]]


In [54]:
#3d array 
a3d = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(a3d)
print(f"Each first row {a3d[:,0,:]}")
print(f"Each first column is {a3d[:,:,0]}")

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Each first row [[1 2]
 [7 8]]
Each first column is [[ 1  3  5]
 [ 7  9 11]]
